# -*- coding: utf-8 -*-
"""listclone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nv3-wmb0eBj6c3FQBmA04x5UrbppIyGo
"""

#cloning or copying a list into another list
things = ["Hat", "Bat", "Cat", "Mat"]
print("The original list 'things' contains the elements:", things)

#logic to copy elements of one list to another
also_things = things
print("The cloned list 'also_things' contains the same elements:",also_things)

print("\nCloning successful!")