# -*- coding: utf-8 -*-
"""tuple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nv3-wmb0eBj6c3FQBmA04x5UrbppIyGo
"""

#program to create a tuple of numbers and print it in reverse.
num = (1,2,3,4,5,6)
print("The original tuple is: ", num)         #normal output
print("The reversed tuple is: ", num[::-1])   #reverse output (start index: end index: step (-1 denotes step in reverse))